
main {
}

event onNote(Note note) {
    Vec2f screenSize = Vec2f(1280.0, 720.0);

    let pitch = (1.0 - (note_pitch(note) as float / 128.0));
    let size = Vec2f(note_duration(note), 1.0 / 128.0) * screenSize;

    loop {
        unless(note_isAlive(note)) { kill }
        
        let position = Vec2f(note_time(note), pitch) * screenSize;

        if(note_isPlaying(note)) {
            let factor = note_playTime(note);
            fillRect(position, size, Color(1f, 1f - factor, 1f - factor));
        }
        else {
            fillRect(position, size, Color(1f, 0f, 0f));
        }
        yield
    }
}


/*
let value = note_pitch(note);
    let step = note_step(note);
    let tick = note_tick(note);
*/